snippets:
  - name: git
    keyword: g
    snippet: git

  - name: git status
    keyword: s
    snippet: status --short --branch
    context:
      lbuffer: '^git\s'

  # snippet with placeholder
  - name: git commit message
    keyword: gcim
    snippet: git commit -m '{{commit_message}}'

  - name: git log
    keyword: l
    snippet: log --oneline --abbrev-commit --date=iso
		# --abbrev-commit : コミットのハッシュを頭の7バイトに短縮
		# --date-iso : 2015-04-14 13:20:45 表示にする
    context:
      lbuffer: '^git\s'




